### ISSUE TITLE
Error while building in xcode

### ISSUE THREAD

**Issue by andyferriby** [lalabuy948/MiniSpaceJourney#5]
Showing All Messages
:-1: Unable to resolve build file: XCBCore.BuildFile (namedReferencesCannotBeResolved) (in target 'MiniSpaceJourney Extension')
<img width="1275" alt="Screenshot 2019-08-14 at 11 29 06" src="https://user-images.githubusercontent.com/21694968/63014586-c5816f00-be86-11e9-9822-cbd04824ba72.png">

**Comment by lalabuy948** [comment]
@andyferriby I guess you forget to add second target, which is watchOS device
