### ISSUE TITLE
Simulator - xcode 11

### ISSUE THREAD

**Issue by xcode-blip** [lalabuy948/MiniSpaceJourney#6]
Just ran your game on xcode simulator, and i get this error while playing the game.

2019-10-08 12:50:59.305870+0100 MiniSpaceJourney WatchKit Extension[36000:4746435] SKTexture: Error loading image resource: "spark"

In your older version the file spark is in the project but in this new update it seems to be missing and causing the game to crash after loosing the game.

Many Thanks

**Comment by lalabuy948** [comment]
@xcode-blip  Thank you for pointing this out,  I will add missing file asap.

**Comment by lalabuy948** [comment]
@xcode-blip sorry for fixing that for so long, added. Now it should be fine. 

Probably you will need to choose spark one more time in `explosion.sks`.
